<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h2 class="text-xl font-semibold">Employees</h2><a href="{{ route('employees.create') }}" class="rounded bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Add employee</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl px-4">
        <div class="mb-4 rounded bg-white p-4 shadow"><div class="grid gap-3 sm:grid-cols-3"><select id="filter-department" class="rounded border-gray-300"><option value="">All departments</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><select id="filter-status" class="rounded border-gray-300"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button id="clear-filters" class="rounded border px-4 py-2">Clear filters</button></div></div>
        <div class="overflow-x-auto rounded bg-white p-4 shadow"><table id="employees-table" class="min-w-full"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Department</th><th>Salary</th><th>Joining date</th><th>Status</th><th>Actions</th></tr></thead></table></div>
    </div></div>
    @push('styles')<link rel="stylesheet" href="https://cdn.datatables.net/2.3.7/css/dataTables.dataTables.min.css">@endpush
    @push('scripts')<script src="https://cdn.datatables.net/2.3.7/js/dataTables.min.js"></script><script>$(function(){const table=$('#employees-table').DataTable({processing:true,serverSide:true,ajax:{url:'{{ route('employees.data') }}',data:d=>{d.department_id=$('#filter-department').val();d.status=$('#filter-status').val();}},columns:[{data:'name'},{data:'email'},{data:'phone'},{data:'department',orderable:false},{data:'salary'},{data:'joining_date'},{data:'status'},{data:'actions',orderable:false,searchable:false}]});$('#filter-department,#filter-status').on('change',()=>table.ajax.reload());$('#clear-filters').on('click',()=>{$('#filter-department,#filter-status').val('');table.ajax.reload();});});</script>@endpush
</x-app-layout>
